<?php


namespace Dohone\PayOut\Dohone\PayOut\Command;


class StartCommandUI extends StartCommand
{

    protected function responseParser($body)
    {
        // TODO: Implement responseParser() method.
    }

    public function get()
    {
        return parent::get(); // TODO: Change the autogenerated stub
    }
}